language: java
addons:
  sonarcloud:
    organization: "tgouvea-github"
jdk: 
  - oraclejdk8
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
